### ISSUE TITLE
wifiwizard

### ISSUE THREAD

**Issue by ifbbprochris** [DynamicRemo/WifiApp#1]
how do I add plugin in this project. 
 I try cordova plugin add https://github.com/parsonsmatt/WifiWizard.git , but it said Repository "https://github.com/parsonsmatt/WifiWizard.git" checked out to git ref "master".

can you help me?

**Comment by ifbbprochris** [comment]
WifiWizard is not defined in wifiservice.js 46

**Comment by ifbbprochris** [comment]
Does it support ios?

**Comment by DynamicRemo** [comment]
@ChrisFuck please elaborate your first two comments, i don't get your concern.
Yes, WifiWizard (Version 0.2.10) is now available on IOS too.

**Comment by Muhan95** [comment]
@DynamicRemo I'm also getting the same problem as Chris:

I've copied all of your files but I get the following error when I try to run it: 
app.js:34 Uncaught TypeError: Cannot read property 'Keyboard' of undefined(anonymous function)
wifiservice.js:46 Uncaught ReferenceError: WifiWizard is not defined(anonymous function)

I'd really appreciate if you could help me out here, thanks.

**Comment by Muhan95** [comment]
@ChrisFuck Have you installed the wifi wizard plugin? That's what I had to do to get it to work.
